// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pht/pet/link_shortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockLinkSaverGetter is an autogenerated mock type for the LinkSaverGetter type
type MockLinkSaverGetter struct {
	mock.Mock
}

type MockLinkSaverGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkSaverGetter) EXPECT() *MockLinkSaverGetter_Expecter {
	return &MockLinkSaverGetter_Expecter{mock: &_m.Mock}
}

// GetClicks provides a mock function with given fields: _a0, _a1
func (_m *MockLinkSaverGetter) GetClicks(_a0 context.Context, _a1 string) (int32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetClicks")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLinkSaverGetter_GetClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClicks'
type MockLinkSaverGetter_GetClicks_Call struct {
	*mock.Call
}

// GetClicks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockLinkSaverGetter_Expecter) GetClicks(_a0 interface{}, _a1 interface{}) *MockLinkSaverGetter_GetClicks_Call {
	return &MockLinkSaverGetter_GetClicks_Call{Call: _e.mock.On("GetClicks", _a0, _a1)}
}

func (_c *MockLinkSaverGetter_GetClicks_Call) Run(run func(_a0 context.Context, _a1 string)) *MockLinkSaverGetter_GetClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLinkSaverGetter_GetClicks_Call) Return(_a0 int32, _a1 error) *MockLinkSaverGetter_GetClicks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLinkSaverGetter_GetClicks_Call) RunAndReturn(run func(context.Context, string) (int32, error)) *MockLinkSaverGetter_GetClicks_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: _a0, _a1
func (_m *MockLinkSaverGetter) GetURL(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLinkSaverGetter_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockLinkSaverGetter_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockLinkSaverGetter_Expecter) GetURL(_a0 interface{}, _a1 interface{}) *MockLinkSaverGetter_GetURL_Call {
	return &MockLinkSaverGetter_GetURL_Call{Call: _e.mock.On("GetURL", _a0, _a1)}
}

func (_c *MockLinkSaverGetter_GetURL_Call) Run(run func(_a0 context.Context, _a1 string)) *MockLinkSaverGetter_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLinkSaverGetter_GetURL_Call) Return(_a0 string, _a1 error) *MockLinkSaverGetter_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLinkSaverGetter_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockLinkSaverGetter_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, url, code
func (_m *MockLinkSaverGetter) Save(ctx context.Context, url string, code string) (*domain.Link, error) {
	ret := _m.Called(ctx, url, code)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Link, error)); ok {
		return rf(ctx, url, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Link); ok {
		r0 = rf(ctx, url, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, url, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLinkSaverGetter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLinkSaverGetter_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - code string
func (_e *MockLinkSaverGetter_Expecter) Save(ctx interface{}, url interface{}, code interface{}) *MockLinkSaverGetter_Save_Call {
	return &MockLinkSaverGetter_Save_Call{Call: _e.mock.On("Save", ctx, url, code)}
}

func (_c *MockLinkSaverGetter_Save_Call) Run(run func(ctx context.Context, url string, code string)) *MockLinkSaverGetter_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLinkSaverGetter_Save_Call) Return(_a0 *domain.Link, _a1 error) *MockLinkSaverGetter_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLinkSaverGetter_Save_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Link, error)) *MockLinkSaverGetter_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLinkSaverGetter creates a new instance of MockLinkSaverGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkSaverGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkSaverGetter {
	mock := &MockLinkSaverGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
