// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "pht/pet/link_shortener/internal/domain"
	db "pht/pet/link_shortener/internal/domain/db"

	mock "github.com/stretchr/testify/mock"
)

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// GetURLAndClicks provides a mock function with given fields: _a0, _a1
func (_m *MockURLRepository) GetURLAndClicks(_a0 context.Context, _a1 string) (string, int32, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetURLAndClicks")
	}

	var r0 string
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, int32, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int32); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockURLRepository_GetURLAndClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLAndClicks'
type MockURLRepository_GetURLAndClicks_Call struct {
	*mock.Call
}

// GetURLAndClicks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockURLRepository_Expecter) GetURLAndClicks(_a0 interface{}, _a1 interface{}) *MockURLRepository_GetURLAndClicks_Call {
	return &MockURLRepository_GetURLAndClicks_Call{Call: _e.mock.On("GetURLAndClicks", _a0, _a1)}
}

func (_c *MockURLRepository_GetURLAndClicks_Call) Run(run func(_a0 context.Context, _a1 string)) *MockURLRepository_GetURLAndClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_GetURLAndClicks_Call) Return(_a0 string, _a1 int32, _a2 error) *MockURLRepository_GetURLAndClicks_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockURLRepository_GetURLAndClicks_Call) RunAndReturn(run func(context.Context, string) (string, int32, error)) *MockURLRepository_GetURLAndClicks_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementClicks provides a mock function with given fields: _a0, _a1
func (_m *MockURLRepository) IncrementClicks(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IncrementClicks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_IncrementClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementClicks'
type MockURLRepository_IncrementClicks_Call struct {
	*mock.Call
}

// IncrementClicks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockURLRepository_Expecter) IncrementClicks(_a0 interface{}, _a1 interface{}) *MockURLRepository_IncrementClicks_Call {
	return &MockURLRepository_IncrementClicks_Call{Call: _e.mock.On("IncrementClicks", _a0, _a1)}
}

func (_c *MockURLRepository_IncrementClicks_Call) Run(run func(_a0 context.Context, _a1 string)) *MockURLRepository_IncrementClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_IncrementClicks_Call) Return(_a0 error) *MockURLRepository_IncrementClicks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_IncrementClicks_Call) RunAndReturn(run func(context.Context, string) error) *MockURLRepository_IncrementClicks_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLink provides a mock function with given fields: _a0, _a1
func (_m *MockURLRepository) SaveLink(_a0 context.Context, _a1 db.CreateLinkParams) (*domain.Link, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveLink")
	}

	var r0 *domain.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateLinkParams) (*domain.Link, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateLinkParams) *domain.Link); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateLinkParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_SaveLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLink'
type MockURLRepository_SaveLink_Call struct {
	*mock.Call
}

// SaveLink is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 db.CreateLinkParams
func (_e *MockURLRepository_Expecter) SaveLink(_a0 interface{}, _a1 interface{}) *MockURLRepository_SaveLink_Call {
	return &MockURLRepository_SaveLink_Call{Call: _e.mock.On("SaveLink", _a0, _a1)}
}

func (_c *MockURLRepository_SaveLink_Call) Run(run func(_a0 context.Context, _a1 db.CreateLinkParams)) *MockURLRepository_SaveLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateLinkParams))
	})
	return _c
}

func (_c *MockURLRepository_SaveLink_Call) Return(_a0 *domain.Link, _a1 error) *MockURLRepository_SaveLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_SaveLink_Call) RunAndReturn(run func(context.Context, db.CreateLinkParams) (*domain.Link, error)) *MockURLRepository_SaveLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClicks provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockURLRepository) UpdateClicks(_a0 context.Context, _a1 int32, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClicks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_UpdateClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClicks'
type MockURLRepository_UpdateClicks_Call struct {
	*mock.Call
}

// UpdateClicks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int32
//   - _a2 string
func (_e *MockURLRepository_Expecter) UpdateClicks(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockURLRepository_UpdateClicks_Call {
	return &MockURLRepository_UpdateClicks_Call{Call: _e.mock.On("UpdateClicks", _a0, _a1, _a2)}
}

func (_c *MockURLRepository_UpdateClicks_Call) Run(run func(_a0 context.Context, _a1 int32, _a2 string)) *MockURLRepository_UpdateClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockURLRepository_UpdateClicks_Call) Return(_a0 error) *MockURLRepository_UpdateClicks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_UpdateClicks_Call) RunAndReturn(run func(context.Context, int32, string) error) *MockURLRepository_UpdateClicks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
