// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_code, long_url) VALUES ($1, $2) RETURNING id, short_code, long_url, clicks
`

type CreateLinkParams struct {
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
}

type CreateLinkRow struct {
	ID        int64  `json:"id"`
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
	Clicks    int32  `json:"clicks"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ShortCode, arg.LongUrl)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
	)
	return i, err
}

const getURLAndClicksByCode = `-- name: GetURLAndClicksByCode :one
SELECT long_url, clicks FROM links WHERE short_code = $1 LIMIT 1
`

type GetURLAndClicksByCodeRow struct {
	LongUrl string `json:"long_url"`
	Clicks  int32  `json:"clicks"`
}

func (q *Queries) GetURLAndClicksByCode(ctx context.Context, shortCode string) (GetURLAndClicksByCodeRow, error) {
	row := q.db.QueryRow(ctx, getURLAndClicksByCode, shortCode)
	var i GetURLAndClicksByCodeRow
	err := row.Scan(&i.LongUrl, &i.Clicks)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE links SET clicks = clicks + 1 WHERE short_code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClicks, shortCode)
	return err
}

const updateClicks = `-- name: UpdateClicks :exec
UPDATE links SET clicks = clicks + $2 WHERE short_code = $1
`

type UpdateClicksParams struct {
	ShortCode string `json:"short_code"`
	Clicks    int32  `json:"clicks"`
}

func (q *Queries) UpdateClicks(ctx context.Context, arg UpdateClicksParams) error {
	_, err := q.db.Exec(ctx, updateClicks, arg.ShortCode, arg.Clicks)
	return err
}
